version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my_database
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  api:
    build: ./api
    container_name: flask_api
    environment:
      MYSQL_HOST: mysql_container
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DB: my_database
    ports:
      - "5000:5000"
    depends_on:
      - mysql

volumes:
  mysql_data:
